name = "Peger"
uuid = "ec7b7d79-dbae-4408-b78a-87ac01e61607"
authors = ["Soeking <great.from.g@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]